{% set name = "xsdba" %}
{% set version = "0.3.1" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xsdba-{{ version }}.tar.gz
  sha256: 9852968e57aff98aab419551b82d23d177533294090c72461d01c8571453f493

build:
  entry_points:
    - xsdba = xsdba.cli:app
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=3.10.1,<4
    - pip >=25.0
  run:
    - python >={{ python_min }}
    - boltons >=20.1
    - bottleneck >=1.3.1
    - cf_xarray >=0.10.0
    - cftime >=1.4.1
    - dask-core >=2024.8.1
    - h5netcdf >=1.3.0
    - jsonpickle >=3.1.0
    - numba >=0.54.1
    - numpy >=1.23.0,<2.0
    - pint >=0.24.3
    - scipy >=1.9.0
    - statsmodels >=0.14.2
    - typer >=0.12.3
    - xarray >=2023.11.0
    - yamale >=5.0.0
  run_constrained:
    - xclim >=0.55.1

test:
  imports:
    - xsdba
  commands:
    - pip check
    - xsdba
    - python -m pytest --numprocesses=auto tests
  requires:
    - python {{ python_min }}
    - coverage >=7.5.0
    - filelock >=3.14.0
    - pip >=25.0
    - pooch >=1.8.0
    - pytest >=8.0.0,<9.0.0
    - pytest-cov >=5.0.0
    - pytest-xdist >=3.2.0
    - xclim >=0.55.1
    - xdoctest >=1.1.5
  source_files:
    - pyproject.toml
    - tests

about:
  summary: Statistical correction and bias adjustment tools for xarray.
  home: https://github.com/Ouranosinc/xsdba
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  description: |
    The xsdba package provides a collection of bias-adjustment methods
    meant to correct for systematic biases found in climate model simulations
    relative to observations.
  doc_url: https://xsdba.readthedocs.io
  dev_url: https://github.com/Ouranosinc/xsdba

extra:
  recipe-maintainers:
    - Zeitsperre
    - coxipi
